# Generated by Django 4.1.2 on 2022-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(upload_to='profile_pic'),
        ),
    ]
