# Generated by Django 4.1.2 on 2022-10-12 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.CharField(max_length=100)),
                ('session_end', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('father', models.CharField(max_length=300)),
                ('mother', models.CharField(max_length=200)),
                ('parent_address', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.session')),
            ],
        ),
    ]
