# Generated by Django 4.1.2 on 2022-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_branch_course_semester_session_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start',
            field=models.DateField(),
        ),
    ]
