# Generated by Django 4.1.2 on 2022-10-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_session_session_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_address',
        ),
    ]
