# Generated by Django 4.1.2 on 2022-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_rename_student_address_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_ph',
            field=models.IntegerField(default=None),
        ),
    ]
