# Generated by Django 4.1.2 on 2022-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_student_parent_ph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_ph',
            new_name='father_ph',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_ph',
            field=models.IntegerField(default=None),
        ),
    ]
