# Generated by Django 4.1.2 on 2022-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_parent_ph_student_father_ph_student_mother_ph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session_year',
        ),
    ]
