# Generated by Django 4.1.2 on 2022-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_rename_session_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='session_end',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='session_start',
            field=models.CharField(max_length=40),
        ),
    ]
