# Generated by Django 4.1.2 on 2022-10-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_session_year_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_ph',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_ph',
            field=models.CharField(max_length=300),
        ),
    ]
