# Generated by Django 4.0.5 on 2022-10-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_remove_student_id_alter_student_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=300),
        ),
    ]
