# Generated by Django 4.1.2 on 2022-10-19 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('ph', models.CharField(default=None, max_length=200)),
                ('dob', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.course')),
            ],
        ),
    ]
