# Generated by Django 4.1.2 on 2022-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='join',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
