# Generated by Django 4.1.2 on 2022-10-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_teacher_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='teacher_id',
        ),
    ]
