# Generated by Django 4.1.2 on 2022-10-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_rename_id_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
