# Generated by Django 4.1.2 on 2022-10-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_teacher_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
