# Generated by Django 4.1.2 on 2022-10-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='server.course')),
            ],
        ),
    ]
