# Generated by Django 4.1.2 on 2022-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='time',
        ),
        migrations.AddField(
            model_name='routine',
            name='end',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='routine',
            name='start',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
