# Generated by Django 4.1.2 on 2022-10-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_remove_routine_time_routine_end_routine_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
