# Generated by Django 4.1.2 on 2022-10-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.subject'),
        ),
    ]
