# Generated by Django 4.1.2 on 2022-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_alter_routine_monday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='monday',
            field=models.CharField(max_length=100),
        ),
    ]
