# Generated by Django 4.1.2 on 2022-10-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_alter_routine_monday'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='server.teacher'),
        ),
    ]
