# Generated by Django 4.1.2 on 2022-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
