# Generated by Django 4.0.5 on 2022-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_remove_subject_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
