# Generated by Django 4.0.5 on 2022-10-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
