# Generated by Django 4.0.5 on 2022-10-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
