# Generated by Django 4.0.5 on 2022-10-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='server.teacher'),
        ),
    ]
