# Generated by Django 4.0.5 on 2022-10-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_remove_routine_branch_remove_routine_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='end',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='start',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='wednesday',
        ),
    ]
