# Generated by Django 4.0.5 on 2022-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_alter_routine_end_alter_routine_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='end',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='friday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='monday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='saturday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='thursday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tuesday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='wednesday',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
