# Generated by Django 4.1.2 on 2022-10-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_alter_routine_end_alter_routine_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine_head',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='routine_head',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.course'),
        ),
        migrations.AlterField(
            model_name='routine_head',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.semester'),
        ),
    ]
