# Generated by Django 4.1.2 on 2022-10-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0049_alter_routine_head_branch_alter_routine_head_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.teacher'),
        ),
    ]
