# Generated by Django 4.0.5 on 2022-10-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_teacher_msg_status_teacher_msg_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_msg',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
    ]
