# Generated by Django 4.1.2 on 2022-11-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0057_alter_teacher_msg_messages_alter_teacher_msg_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_msg',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Teacher_see_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.teacher_msg')),
                ('teacher', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher')),
            ],
        ),
    ]
