# Generated by Django 4.1.2 on 2022-11-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0058_remove_teacher_msg_teacher_teacher_see_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_see_msg',
        ),
    ]
