# Generated by Django 4.1.2 on 2022-11-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0060_teacher_see_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_msg',
            name='msg',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacher_msg',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher_msg',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Teacher_see_msg',
        ),
    ]
