# Generated by Django 4.1.2 on 2022-11-05 16:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0062_remove_teacher_msg_msg_remove_teacher_msg_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_msg',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_msg',
            name='messages',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Student_see_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student_msg')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
