# Generated by Django 4.1.2 on 2022-11-06 16:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0063_student_msg_status_alter_student_msg_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_leave_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('msg', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.teacher')),
            ],
        ),
    ]
