# Generated by Django 4.1.2 on 2022-11-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0064_teacher_leave_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
