# Generated by Django 4.1.2 on 2022-11-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0065_alter_teacher_leave_apply_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_leave_apply',
            old_name='user',
            new_name='user_id',
        ),
    ]
