# Generated by Django 4.1.2 on 2022-11-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0066_rename_user_teacher_leave_apply_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
    ]
