# Generated by Django 4.1.2 on 2022-11-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0067_alter_teacher_leave_apply_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='start',
            field=models.DateField(),
        ),
    ]
