# Generated by Django 4.1.2 on 2022-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0068_alter_teacher_leave_apply_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher_leave_apply',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
