# Generated by Django 4.1.2 on 2022-11-07 13:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0071_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('msg', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
