# Generated by Django 4.0.5 on 2022-11-08 10:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0072_student_leave_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('msg', ckeditor.fields.RichTextField()),
                ('replay', ckeditor.fields.RichTextField(blank=True, max_length=400, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher')),
            ],
        ),
    ]
