# Generated by Django 4.1.2 on 2022-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0074_alter_teachersfeedback_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersfeedback',
            name='replay',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
