# Generated by Django 4.1.2 on 2022-11-08 22:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0075_alter_teachersfeedback_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('msg', ckeditor.fields.RichTextField()),
                ('replay', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
