# Generated by Django 4.1.2 on 2022-11-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0078_attendance_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_chields',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
