# Generated by Django 4.1.2 on 2022-11-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0079_alter_attendance_chields_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance_chields',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
