# Generated by Django 4.1.2 on 2022-11-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_alter_attendance_date_alter_attendance_chields_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='section',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sem',
        ),
    ]
