# Generated by Django 4.1.2 on 2022-11-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0082_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_chields',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.subject'),
        ),
    ]
