# Generated by Django 4.1.2 on 2022-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0083_attendance_chields_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_chields',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
