# Generated by Django 4.1.2 on 2022-11-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0084_alter_attendance_chields_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_chields',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Student_online_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('Subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.subject')),
            ],
        ),
    ]
