# Generated by Django 4.1.2 on 2022-11-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0085_alter_attendance_chields_date_student_online_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_online_class',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
    ]
