# Generated by Django 4.1.2 on 2022-11-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0086_student_online_class_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_online_class',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='student_online_class',
            old_name='Subject',
            new_name='subject',
        ),
    ]
