# Generated by Django 4.1.2 on 2022-11-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0087_alter_student_online_class_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_online_class',
            name='semester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.semester'),
        ),
    ]
