# Generated by Django 4.1.2 on 2022-11-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0088_student_online_class_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_online_class',
            name='semester',
        ),
    ]
