# Generated by Django 4.1.2 on 2022-11-22 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0090_student_online_class_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_online_class',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.semester'),
        ),
    ]
