# Generated by Django 4.1.2 on 2022-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0093_alter_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comment',
            old_name='like',
            new_name='user',
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Blog_like',
        ),
    ]
