# Generated by Django 4.1.2 on 2022-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0094_rename_like_blog_comment_user_blog_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
