# Generated by Django 4.1.2 on 2022-11-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0095_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='head',
            field=models.CharField(max_length=400),
        ),
    ]
