# Generated by Django 4.1.2 on 2022-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0096_alter_blog_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=200)),
                ('no_of_bed', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
