# Generated by Django 4.1.2 on 2022-11-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0097_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
