# Generated by Django 4.1.2 on 2022-11-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0098_hostel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available_bed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
