# Generated by Django 4.1.2 on 2022-11-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0099_hostel_available_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=400)),
                ('bus_num', models.IntegerField(max_length=30)),
                ('driver_name', models.CharField(max_length=400)),
                ('driver_ph1', models.IntegerField(max_length=30)),
                ('driver_ph2', models.IntegerField(blank=True, max_length=30, null=True)),
                ('license', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=300)),
            ],
        ),
    ]
