# Generated by Django 4.1.2 on 2022-11-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0100_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='bus_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='driver_ph1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='driver_ph2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
