# Generated by Django 4.1.2 on 2022-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0101_alter_transport_bus_num_alter_transport_driver_ph1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.teacher')),
            ],
        ),
    ]
