# Generated by Django 4.1.2 on 2022-11-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0102_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.branch'),
        ),
    ]
