# Generated by Django 4.0.5 on 2022-11-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0103_alter_hod_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default='Not mentions', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.subject'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.teacher'),
        ),
        migrations.AlterField(
            model_name='attendance_chields',
            name='student',
            field=models.ForeignKey(default='Not mentions', on_delete=django.db.models.deletion.CASCADE, to='server.student'),
        ),
        migrations.AlterField(
            model_name='attendance_chields',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.subject'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hod',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.teacher'),
        ),
        migrations.AlterField(
            model_name='routine_head',
            name='branch',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='routine_head',
            name='course',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.course'),
        ),
        migrations.AlterField(
            model_name='routine_head',
            name='sem',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.session_year'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(default='Not mention', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.course'),
        ),
    ]
