# Generated by Django 4.0.5 on 2022-11-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0105_alter_attendance_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.branch'),
        ),
    ]
