# Generated by Django 4.0.5 on 2022-11-29 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0106_alter_hod_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine_head',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.course'),
        ),
    ]
