# Generated by Django 4.0.5 on 2022-11-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0108_alter_attendance_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_chields',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.subject'),
        ),
    ]
