# Generated by Django 4.0.5 on 2022-12-04 22:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0109_alter_attendance_chields_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ('start',)},
        ),
        migrations.AlterField(
            model_name='hod',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='hod',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.teacher'),
        ),
        migrations.CreateModel(
            name='Group_discussion_replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
        migrations.CreateModel(
            name='Group_discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_discussion')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.course')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
