# Generated by Django 4.0.5 on 2022-12-05 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0111_group_discussion_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_discussion',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.branch'),
        ),
        migrations.AlterField(
            model_name='group_discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.course'),
        ),
        migrations.AlterField(
            model_name='group_discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.student'),
        ),
        migrations.AlterField(
            model_name='group_discussion',
            name='user_type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
