# Generated by Django 4.0.5 on 2022-12-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0112_alter_group_discussion_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_discussion',
            old_name='Branch',
            new_name='branch',
        ),
    ]
