# Generated by Django 4.0.5 on 2022-12-05 18:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0114_alter_group_discussion_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_discussion',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
