# Generated by Django 4.0.5 on 2022-12-05 22:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0115_alter_group_discussion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_discussion_replay',
            name='gd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.group_discussion'),
        ),
        migrations.AddField(
            model_name='group_discussion_replay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_discussion'),
        ),
        migrations.AlterField(
            model_name='group_discussion_replay',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_discussion_replay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.student'),
        ),
    ]
