# Generated by Django 4.0.5 on 2022-12-09 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0117_quiz_quiz_result_quiz_qn_quiz_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.branch'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.semester'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
    ]
