# Generated by Django 4.0.5 on 2022-12-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0118_quiz_branch_quiz_course_quiz_sem_alter_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_ans',
            name='correctB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz_ans',
            name='correctC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz_ans',
            name='correctD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz_ans',
            name='textB',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz_ans',
            name='textC',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quiz_ans',
            name='textD',
            field=models.CharField(default='', max_length=300),
        ),
    ]
