# Generated by Django 4.0.5 on 2022-12-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0119_quiz_ans_correctb_quiz_ans_correctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ans',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
