# Generated by Django 4.0.5 on 2022-12-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0120_alter_quiz_ans_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ans',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.quiz_qn'),
        ),
    ]
