# Generated by Django 4.0.5 on 2022-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0121_alter_quiz_ans_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ans',
            name='correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctB',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctC',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctD',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='text',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textB',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textC',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textD',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
