# Generated by Django 4.0.5 on 2022-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0122_alter_quiz_ans_correct_alter_quiz_ans_correctb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ans',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textB',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textC',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='textD',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
