# Generated by Django 4.0.5 on 2022-12-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0123_alter_quiz_ans_text_alter_quiz_ans_textb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_qn',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.quiz'),
        ),
    ]
