# Generated by Django 4.0.5 on 2022-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0124_alter_quiz_qn_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ans',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctB',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz_ans',
            name='correctD',
            field=models.BooleanField(default=False),
        ),
    ]
