# Generated by Django 4.0.5 on 2022-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0128_quiz_question_declare_quiz_result_declare'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
