# Generated by Django 4.0.5 on 2022-12-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0130_alter_quiz_date_alter_quiz_question_declare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_declare',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='result_declare',
        ),
    ]
