# Generated by Django 4.0.5 on 2022-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0131_remove_quiz_date_remove_quiz_question_declare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_show', models.BooleanField(default=False)),
                ('qn_show', models.BooleanField(default=False)),
            ],
        ),
    ]
