# Generated by Django 4.0.5 on 2022-12-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0132_quiz_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz_setting',
        ),
    ]
