# Generated by Django 4.0.5 on 2022-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0133_delete_quiz_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_qn',
            field=models.BooleanField(default=False),
        ),
    ]
