# Generated by Django 4.0.5 on 2022-12-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0134_quiz_show_qn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='show_qn',
        ),
    ]
