# Generated by Django 4.0.5 on 2022-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0135_remove_quiz_show_qn'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_qn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_res',
            field=models.BooleanField(default=False),
        ),
    ]
