# Generated by Django 4.0.5 on 2022-12-27 13:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0138_quiz_result_result_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(auto_now_add=True)),
                ('online', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Submit_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment')),
                ('offline', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('teacher_accept', models.BooleanField(default=False)),
                ('teacher_mark', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
