# Generated by Django 4.0.5 on 2022-12-27 13:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0139_assignment_submit_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_see_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_accept', models.BooleanField(default=False)),
                ('teacher_mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_submit_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment')),
                ('offline', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Submit_Assignment',
        ),
        migrations.AddField(
            model_name='assignment_see_teacher',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.assignment_submit_student'),
        ),
    ]
