# Generated by Django 4.0.5 on 2022-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0140_assignment_see_teacher_assignment_submit_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_date',
            field=models.DateField(),
        ),
    ]
