# Generated by Django 4.0.5 on 2022-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0143_alter_assignment_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_date',
            field=models.CharField(max_length=200),
        ),
    ]
