# Generated by Django 4.0.5 on 2022-12-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0145_rename_assignment_see_teacher_assignment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_start',
            field=models.BooleanField(default=False),
        ),
    ]
