# Generated by Django 4.0.5 on 2022-12-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0150_alter_assignment_result_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submit_student',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submit_student', to='server.assignment'),
        ),
    ]
