# Generated by Django 4.0.5 on 2022-12-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0156_subject_sem_alter_subject_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sem',
        ),
    ]
