# Generated by Django 4.0.5 on 2022-12-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0158_starstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_teacher_to_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='teacher_notice')),
                ('date', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.course')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.semester')),
            ],
        ),
    ]
