# Generated by Django 4.0.5 on 2022-12-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0159_notice_teacher_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_teacher_to_student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.teacher'),
        ),
    ]
