from unicodedata import name
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views_hod,views_student,views, views_teacher

urlpatterns = [
    path('admin/', admin.site.urls),

    # Common
    path('',views.log_in,name='log_in'),
    path('log_out/',views.log_out,name='log_out'),
    path('profile_update/',views.profile_update,name='profile_update'),
    path('change_password/',views.change_password,name='change_password'),
    path('blog_add/',views.blog_add,name='blog_add'),
    path('blog/',views.blog,name='blog'),
    path('blog_view/<url>',views.blog_view,name='blog_view'),
    path('blog_remove_comment/<url>',views.remove_blog_comment,name='remove_blog_comment'),
    path('blog_remove/<url>',views.remove_blog,name="remove_blog"),
    path('blog_edit/<url>',views.edit_blog,name="edit_blog"),
     path('hostel_room',views.hostel_room,name='hostel_room'),
    path('transport_list/',views.transport_list,name='transport'),
    path('branch/',views.branch_list,name='branch_all'),
    path('course/',views.course_list,name = 'course_all'),


  


# ..................HOD URL...............
   path('hod/dashboard/',views_hod.dashboard,name='hod_dashboard'),
   path('hod/add_student/',views_hod.student_add,name='add_student'),
   path('hod/student_list/',views_hod.student_list,name='student_list'),
   path('hod/student_details/<url>',views_hod.student_details,name='student_details'),
   path('hod/student_update/<url>',views_hod.student_update,name='student_update'),
   path('hod/student_remove/<url>',views_hod.remove_students,name='student_remove'),
   path('hod/add_course/',views_hod.course_add,name='course_add'),
   path('hod/course_remove/<url>',views_hod.course_remove,name='course_remove'),
   path('hod/course_edit/<url>',views_hod.course_edit,name='course_edit'),
   path('hod/branch_add/',views_hod.branch_add,name = 'branch_add'),
   path('hod/branch_edit/<url>',views_hod.branch_edit,name='branch_edit'),
   path('hod/branch_remove/<url>',views_hod.branch_remove,name='branch_remove'),
   path('hod/teacher_add/',views_hod.Teacher_add.as_view(),name='teacher_add'),
   path('hod/teacher_list/',views_hod.Teacher_list.as_view(),name='teacher_list'),
   path('hod/teacher_details/<url>',views_hod.Teacher_details.as_view(),name='teacher_details'),
   path('hod/teacher_update/<url>',views_hod.Teacher_update.as_view(),name='teacher_update'),
   path('hod/teacher_remove/<url>',views_hod.teacher_remove,name='teacher_remove'),
   path('hod/subject_add/',views_hod.Subject_add,name='subject_add'),
   path('hod/subject_list/',views_hod.subject_list,name='subject_list') ,
   path('hod/subject_update/<url>',views_hod.subject_update,name = 'subject_update'),
   path('hod/subject_remove/<url>',views_hod.subject_remove,name='remove_subject'),
   path('hod/session_list/',views_hod.session_list,name = 'session_list'),
   path('hod/session_update/<url>',views_hod.session_update,name='session_update'),
   path('hod/session_remove/<url>',views_hod.session_remove,name='session_remove'),
   path('hod/routine_add',views_hod.routine_add.as_view(),name='routine_add'),
   path('hod/routine_show',views_hod.routine_show,name='routine_show'),
   path('hod/routine_head_edit/<url>',views_hod.routine_head_update,name='routine_head_edit'),
    path('hod/routine_update/<url>/<url2>',views_hod.routine_update,name='routine_update'),
    path('hod/routine_delete/<url>',views_hod.routine_remove,name='routine_delete'),
    path('hod/notice_teacher/',views_hod.notice_teacher,name='notice_teacher'),
    path('hod/notice_teacher_list/',views_hod.notice_teacher_list,name = 'notice_teacher_list'),
    path('hod/notice_teacher_view/<url>',views_hod.notice_teacher_view,name = 'notice_teacher_view'),
    path('hod/notice_teacher_remove/<url>',views_hod.notice_teacher_remove,name = 'notice_teacher_remove'),
    path('hod/notice_student/',views_hod.notice_student,name = 'notice_student'),
    path('hod/notice_student_list/',views_hod.notice_student_list,name='notice_student_list'),
    path('hod/notice_student_remove/<url>',views_hod.notice_student_remove,name='notice_student_remove'),
    path('hod/notice_student_view/<url>',views_hod.notice_student_view,name = '/notice_student_view'),
    path('hod/leave_teacher',views_hod.leave_teacher,name='leave_teacher'),
    path('hod/leave_teacher_accept/<url>',views_hod.leave_teacher_accept,name='leave_teacher_accept'),
    path('hod/leave_teacher_reject/<url>',views_hod.leave_teacher_reject,name = 'leave_teacher_reject'),
    path('hod/leave_student',views_hod.leave_student,name='leave_student'),
    path('hod/leave_student_accept/<url>',views_hod.leave_student_accept,name='leave_student_accept'),
    path('hod/leave_student_reject/<url>',views_hod.leave_student_reject,name='leave_student_reject'),
    path('hod/feedback_teacher/',views_hod.teacher_feedback,name = 'feedback_teacher'),
    path('hod/feedback_teacher_clear/',views_hod.Teacher_feedback_clear,name = 'feedback_teacher_clear'),
    path('hod/feedback_teacher_delete/<url>',views_hod.Teacher_feedback_delete,name = 'feedback_teacher_delete'),
    path('hod/feedback_teacher_replay/<url>',views_hod.Teacher_feedback_replay,name = 'feedback_teacher_replay'),
    path('hod/feedback_teacher_status/<url>',views_hod.Teacher_feedback_status,name = 'feedback_teacher_status'),
    path('hod/feedback_student',views_hod.student_feedback,name = 'feedback_student'),
    path('hod/feedback_student_clear/',views_hod.Student_feedback_clear,name = 'feedback_student_clear'),
    path('hod/feedback_student_status/<url>',views_hod.student_feedback_status,name = 'feedback_student_status'),
    path('hod/feedback_student_replay/<url>',views_hod.student_feedback_replay,name = 'feedback_student_replay'),
    path('hod/feedback_student_delete/<url>',views_hod.student_feedback_delete,name = 'feedback_student_delete'),
    path('hod/hostel_add.html',views_hod.hostel_add,name='hostel_add'),
    path('hod/hostel_list',views_hod.hostel_list,name='hostel_list'),
    path('hod/hostel_details/<url>',views_hod.hostel_details,name="hostel_details"),
    path('hod/hostel_student_remove/<url>',views_hod.hostel_student_remove,name='hostel_student_remove'),
    path('hod/hostel_remove/<url>',views_hod.hostel_remove,name='hostel_remove'),
    path('hod/transport_add/',views_hod.transport_add,name='transport_add'),
    path('hod/transport_list/',views_hod.transport_list,name='transport_list'),
    path('hod/transport_edit/<url>',views_hod.transport_edit,name='transport_edit'),
    path('hod/transport_remove/<url>',views_hod.transport_remove,name = 'transport_remove'),
    path('hod/quiz_list/',views_hod.quiz_list,name='hod_quiz_list'),
    path('hod/quiz_view/<url>',views_hod.quiz_view,name='hod_quiz_view'),
    path('hod/assignment_list/',views_hod.assignment_list,name='hod_assignment_list'),
    path('hod/assignment_view/<url>',views_hod.assignment_view,name='hod_assignment_view'),
    path('hod/setting',views_hod.setting,name='hod_setting'),
    path('hod/changed_branch_setting',views_hod.changed_branch,name='changed_branch_setting'),
    path('hod/setting_remove__last_year_student',views_hod.setting_remove__last_year_student,name='setting_remove__last_year_student'),

    # ----------------------------TEACHER URL----------------------------
    
path('teacher/home/',views_teacher.home,name='teacher_home'),
path('teacher/hod_notify/',views_teacher.hod_notify,name = 'hod_notify_list'),
path('teacher/hod_notify_show/<url>',views_teacher.hod_notify_show,name='hod_notify_show'),
path('teacher/leave_apply/',views_teacher.leave_apply,name='teacher_leave_apply'),
path('teacher/leave_list/',views_teacher.leave_list,name='teacher_leave_list'),
path('teacher/leave_list_remove/<url>',views_teacher.leave_list_remove,name='teacher_leave_list_remove'),
path('teacher/view_leave/<url>',views_teacher.view_leave,name='teacher_view_leave'),
path('teacher/feedback/',views_teacher.feedback,name = 'teacher_feedback'),
path('teacher/feedback_list/',views_teacher.feedback_list,name='teacher_feedback_list'),
path('teacher/remove_feedback/<url>',views_teacher.feedback_remove,name='teacher_feedback_remove'),
path('teacher/feedback_view/<url>',views_teacher.feedback_view,name ="teacher_feedback_view"),
path('teacher/take_attendance',views_teacher.take_attendance,name = 'take_attendance'),
path('teacher/attendance_search_student/<branch>/<course>/<sub>/<sem>',views_teacher.attendance_search_student,name='attendance_search_student'),
path('teacher/attendance_show/<sub>',views_teacher.attendance_show,name = 'attendance_show'),
path('teacher/online_class',views_teacher.online_class,name='online_class'),
path('teacher/online_class_list',views_teacher.online_class_list,name='online_class_list'),
path('teacher/online_class_view/<url>',views_teacher.online_class_view,name='online_class_view'),
path('teacher/online_class_remove/<url>',views_teacher.online_class_remove,name='online_class_remove'),
path('teacher/quiz_add',views_teacher.quiz_add,name = 'quiz_add'),
path('teacher/quiz_list',views_teacher.quiz_list,name='quiz_list'),
path('teacher/quiz_qn_add/<url>',views_teacher.quiz_qn_add,name='quiz_qn_add'),
path('teacher/quiz_edit/<url>',views_teacher.quiz_edit,name='quiz_edit'),
path('teacher/quiz_delete/<url>',views_teacher.quiz_delete,name='quiz_delete'),
path('teacher/quiz_qn_view/<url>',views_teacher.quiz_qn_view,name = 'teacher_quiz_qn_view'),
path('teacher/quiz_qn_delete/<url>',views_teacher.quiz_qn_delete,name = 'teacher_quiz_qn_delete'),
path('teacher/quiz_result_view/<url>',views_teacher.quiz_result_view,name='quiz_result_view'),
path('teacher/assignment_create',views_teacher.assignment_create,name='teacher_assignment_create'),
path('teacher/assignment_list/',views_teacher.assignment_list,name='teacher_assignment_list'),
path('teacher/assignment_edit/<url>',views_teacher.assignment_edit,name='teacher_assignment_edit'),
path('teacher/assignment_remove/<url>',views_teacher.assignment_remove,name='teacher_assignment_remove'),
path('teacher/assignment_view/<url>',views_teacher.assignment_view,name='teacher_assignment_view'),
path('teacher/assignment_result/',views_teacher.assignment_result,name='teacher_assignment_result'),
path('teacher/star_student/',views_teacher.star_student,name='teacher_star_student'),
path('teacher/star_student_remove/<url>',views_teacher.star_student_remove,name='teacher_star_student_remove'),
path('teacher/notice_to_student_remove/<url>',views_teacher.notice_to_student_remove,name='teacher_notice_to_student_remove'),

# -----------------------------------STUDENT URL---------------------------------
path('student/home/',views_student.home,name='student_home'),
path('student/hod_notify/',views_student.student_notify,name = 'student_notify'),
path('student/student_notify_show/<url>',views_student.student_notify_show,name='student_notify_show'),
path('student/leave_apply/',views_student.leave_apply,name='student_leave_apply'),
path('student/leave_list',views_student.leave_list,name='student_leave_list'),
path('student/view_leave/<url>',views_student.view_leave,name='student_view_leave'),
path('student/leave_list_remove/<url>',views_student.leave_list_remove,name='student_leave_list_remove'),
path('student/feedback/',views_student.feedback,name='student_feedback'),
path('student/feedback_list/',views_student.feedback_list,name='student_feedback_list'),
path('student/remove_feedback/<url>',views_student.feedback_remove,name = 'student_feedback_remove'),
path('student/feedback_view/<url>',views_student.feedback_view,name ="student_feedback_view"),
path('student/student_see_routine',views_student.routine,name='student_see_routine'),
path('student/teacher_details/<url>',views_student.Teacher_details,name='student_see_teacher_details'),
path('student/student_see_attendance',views_student.student_see_attendance,name='student_see_attendance'),
path('student/online_class/',views_student.online_class,name='student_online_class'),
path('student/gd/',views_student.group_discuss,name='student_group_discuss'),
path('student/gd_add',views_student.group_discuss_add,name='student_group_discuss_add'),
path('student/gd_replay/<url>',views_student.group_discuss_replays,name='student_group_discuss_replay'),
path('student/gd_discuss_remove/<url>',views_student.group_discuss_remove,name='gd_discuss_remove'),
path('student/gd_discuss_replay_remove/<url>',views_student.group_discuss_replay_remove,name='group_discuss_replay_remove'),
path('student/quiz/',views_student.quiz,name='student_quiz'),
path('student/quiz_qn/<url>',views_student.quiz_qn_test,name='student_quiz_qn_test'),
path('student/quiz_end_page/',views_student.quiz_end_page,name='student_quiz_end_page'),
path('student/quiz_view_page/<url>',views_student.quiz_view_page,name='student_quiz_view_page'),
path('student/assignment_list/',views_student.assignment_list,name='student_assignment_list'),
path('student/assignment_view/<url>',views_student.assignment_view,name='student_assignment_view'),
path('student/assignment_edit/<url>',views_student.assignment_edit,name='student_assignment_edit'),
path('student/assignment_result/',views_student.assignment_result,name='student_assignment_result'),




]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
